{"name": "test_get_user_detail", "status": "broken", "statusDetails": {"message": "TypeError: 'Response' object is not callable", "trace": "def test_get_user_detail():\n        response = get_employee()\n        print(response)\n    \n    \n    \n        # Assertion for Status Code\n>       assert response(\"status_code\") == 200, f\"Expected status code 200, but got {response.status_code}\"\nE       TypeError: 'Response' object is not callable\n\ntest_Employee_creation.py:16: TypeError"}, "attachments": [{"name": "stdout", "source": "50b05185-7312-4789-8acb-6301ad4e0df1-attachment.txt", "type": "text/plain"}], "start": 1702587005519, "stop": 1702587005541, "uuid": "ada329d5-6803-48d9-80c0-2a4a0684087b", "historyId": "1f178cc2728e059e7978b806cea60ec7", "testCaseId": "1f178cc2728e059e7978b806cea60ec7", "fullName": "test_Employee_creation#test_get_user_detail", "labels": [{"name": "suite", "value": "test_Employee_creation"}, {"name": "host", "value": "DESKTOP-88G0BTK"}, {"name": "thread", "value": "16496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Employee_creation"}]}