{"name": "test_get_user_detail", "status": "broken", "statusDetails": {"message": "TypeError: 'Response' object is not callable", "trace": "def test_get_user_detail():\n        response = get_employee()\n        print(response)\n    \n    \n    \n        # Assertion for Status Code\n>       assert response(\"status_code\") == 200, f\"Expected status code 200, but got {response.status_code}\"\nE       TypeError: 'Response' object is not callable\n\ntest_Employee_creation.py:16: TypeError"}, "attachments": [{"name": "stdout", "source": "a102e16d-001c-4398-ae62-702cec851cf9-attachment.txt", "type": "text/plain"}], "start": 1702587012368, "stop": 1702587012376, "uuid": "53a0c4a1-8741-4d23-a8f7-0813f9b564bc", "historyId": "1f178cc2728e059e7978b806cea60ec7", "testCaseId": "1f178cc2728e059e7978b806cea60ec7", "fullName": "test_Employee_creation#test_get_user_detail", "labels": [{"name": "suite", "value": "test_Employee_creation"}, {"name": "host", "value": "DESKTOP-88G0BTK"}, {"name": "thread", "value": "3116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Employee_creation"}]}